In [2]:
import numpy as np
import torch as pt

In [3]:
x1 = np.array([[0,1,2],[3,4,5], [6,7,8]])
x2 = np.array([[-1], [1], [-2]])

In [4]:
pt.matmul(pt.tensor(x1), pt.tensor(x2))

tensor([[ -3],
        [ -9],
        [-15]])

In [6]:
id = np.array([[1,0,0], [0,1,0], [0,0,1]])
np.dot(id, x2)

array([[-1],
       [ 1],
       [-2]])

In [7]:
x3 = np.array([[-1, 0], [1, 1], [-2, 2]])
np.dot(x1, x3)

array([[ -3,   5],
       [ -9,  14],
       [-15,  23]])